move docker things to docker/

diff --git a/docker/dvim b/docker/dvim
--- a/docker/dvim
+++ b/docker/dvim
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 
 if [ -z "$1" ]; then
-    echo "Usage: droot <working directory>"
-    exit 1
+	echo "Usage: droot <working directory>"
+	exit 1
 fi
 
 if [ -z "$(docker images -q dvim)" ]; then
-    echo "dvim image not found. Building..."
-    docker buildx build --build-arg USER=$USER -t dvim .
+	echo "dvim image not found. Building..."
+	docker buildx build --build-arg USER=$USER -t dvim .
 fi
 
 WORKDIR=$1
